DROP VIEW IF EXISTS public.vw_orders_unified;

CREATE VIEW public.vw_orders_unified AS
SELECT
  c.codigo,
  c.representante,
  c.ordem_servico_ssgen,
  c.data AS data_cadastro,
  c.ordem_servico_neogen,
  c.cpf_cnpj,
  c.ie_rg,
  c.coordenador,
  c.nome AS cliente_nome,
  c.status AS cliente_status,
  c.id_conta_ssgen,
  c.created_at AS client_created_at,
  c.updated_at,
  so.id AS ordem_id,
  so.nome_produto,
  so.numero_amostras,
  so.numero_nf_neogen,
  so.cra_data,
  so.cra_status,
  so.envio_planilha_data,
  so.envio_planilha_status,
  so.envio_planilha_status_sla,
  so.vri_data,
  so.vri_n_amostras,
  so.vri_resolvido_data,
  so.vri_status_sla,
  so.lpr_data,
  so.lpr_n_amostras,
  so.lpr_status_sla,
  so.envio_resultados_ordem_id,
  so.envio_resultados_data,
  so.envio_resultados_previsao,
  so.envio_resultados_status,
  so.envio_resultados_status_sla,
  so.envio_resultados_data_prova,
  so.cliente_lat,
  so.cliente_lon,
  so.prioridade,
  so.flag_reagendamento,
  so.issue_text,
  so.dt_faturamento,
  so.dt_receb_resultados,
  so.created_at AS order_created_at,
  so.updated_at AS order_updated_at
FROM public.clients c
LEFT JOIN public.service_orders so
  ON c.ordem_servico_ssgen = so.ordem_servico_ssgen;
