// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cevsigsqiroeomtbrzpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNldnNpZ3NxaXJvZW9tdGJyenBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MDU3NzQsImV4cCI6MjA3NzI4MTc3NH0.ONNsDNzS6e6gKXU7DoUyzmYlTU_n0VElOvpt914yGbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});